-- =====================================================
-- CAMBIOS EN BASE DE DATOS PARA SUPABASE - FLOTA v.3
-- =====================================================
-- Ejecutar en el SQL Editor de Supabase

-- =====================================================
-- 1. CREAR NUEVAS TABLAS DE CATÁLOGOS
-- =====================================================

-- Tabla de carrocerías
CREATE TABLE IF NOT EXISTS public.carrocerias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

-- Tabla de colores
CREATE TABLE IF NOT EXISTS public.colores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

-- Tabla de combustibles
CREATE TABLE IF NOT EXISTS public.combustibles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

-- Tabla de transmisiones
CREATE TABLE IF NOT EXISTS public.transmisiones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

-- Tabla de tracciones
CREATE TABLE IF NOT EXISTS public.tracciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

-- Tabla de estados actuales
CREATE TABLE IF NOT EXISTS public.estados_actuales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE
);

-- Tabla de vendedores
CREATE TABLE IF NOT EXISTS public.vendedores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    telefono text,
    email text
);

-- Tabla de grupos de WhatsApp
CREATE TABLE IF NOT EXISTS public.whatsapp_grupos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    group_id text NOT NULL UNIQUE
);

-- Tabla de apoderados
CREATE TABLE IF NOT EXISTS public.apoderados (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arrendadora_id bigint NOT NULL,
    nombre text NOT NULL,
    identificacion text UNIQUE,
    FOREIGN KEY (arrendadora_id) REFERENCES public.arrendadoras(id)
);

-- =====================================================
-- 2. MODIFICAR TABLA ARRENDADORAS
-- =====================================================

-- Agregar campos faltantes a arrendadoras
ALTER TABLE public.arrendadoras 
ADD COLUMN IF NOT EXISTS apoderado text,
ADD COLUMN IF NOT EXISTS cedula_apoderado text;

-- =====================================================
-- 3. MODIFICAR TABLA VEHICULOS
-- =====================================================

-- Agregar nuevos campos a la tabla vehiculos
ALTER TABLE public.vehiculos 
ADD COLUMN IF NOT EXISTS estatus text,
ADD COLUMN IF NOT EXISTS ubicacion text,
ADD COLUMN IF NOT EXISTS renta_semanal numeric,
ADD COLUMN IF NOT EXISTS plazo_semanas smallint,
ADD COLUMN IF NOT EXISTS cliente_actual text,
ADD COLUMN IF NOT EXISTS valor_adquisicion numeric,
ADD COLUMN IF NOT EXISTS fecha_adquisicion date,
ADD COLUMN IF NOT EXISTS grupo_whatsapp text,
ADD COLUMN IF NOT EXISTS carroceria_id bigint,
ADD COLUMN IF NOT EXISTS color_id bigint,
ADD COLUMN IF NOT EXISTS combustible_id bigint,
ADD COLUMN IF NOT EXISTS transmision_id bigint,
ADD COLUMN IF NOT EXISTS traccion_id bigint,
ADD COLUMN IF NOT EXISTS apoderado_id bigint,
ADD COLUMN IF NOT EXISTS vendedor_id bigint,
ADD COLUMN IF NOT EXISTS whatsapp_grupo_id bigint,
ADD COLUMN IF NOT EXISTS estado_actual_id bigint;

-- Agregar foreign keys (con manejo de errores)
DO $$
BEGIN
    -- Carrocería
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_carroceria_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_carroceria_id_fkey 
            FOREIGN KEY (carroceria_id) REFERENCES public.carrocerias(id);
    END IF;
    
    -- Color
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_color_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_color_id_fkey 
            FOREIGN KEY (color_id) REFERENCES public.colores(id);
    END IF;
    
    -- Combustible
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_combustible_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_combustible_id_fkey 
            FOREIGN KEY (combustible_id) REFERENCES public.combustibles(id);
    END IF;
    
    -- Transmisión
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_transmision_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_transmision_id_fkey 
            FOREIGN KEY (transmision_id) REFERENCES public.transmisiones(id);
    END IF;
    
    -- Tracción
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_traccion_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_traccion_id_fkey 
            FOREIGN KEY (traccion_id) REFERENCES public.tracciones(id);
    END IF;
    
    -- Apoderado
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_apoderado_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_apoderado_id_fkey 
            FOREIGN KEY (apoderado_id) REFERENCES public.apoderados(id);
    END IF;
    
    -- Vendedor
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_vendedor_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_vendedor_id_fkey 
            FOREIGN KEY (vendedor_id) REFERENCES public.vendedores(id);
    END IF;
    
    -- WhatsApp grupo
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_whatsapp_grupo_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_whatsapp_grupo_id_fkey 
            FOREIGN KEY (whatsapp_grupo_id) REFERENCES public.whatsapp_grupos(id);
    END IF;
    
    -- Estado actual
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'vehiculos_estado_actual_id_fkey') THEN
        ALTER TABLE public.vehiculos ADD CONSTRAINT vehiculos_estado_actual_id_fkey 
            FOREIGN KEY (estado_actual_id) REFERENCES public.estados_actuales(id);
    END IF;
END $$;

-- =====================================================
-- 4. INSERTAR DATOS INICIALES EN CATÁLOGOS
-- =====================================================

-- Insertar colores básicos
INSERT INTO public.colores (nombre) VALUES 
    ('Blanco'), ('Negro'), ('Gris'), ('Plateado'), ('Azul'), 
    ('Rojo'), ('Verde'), ('Amarillo'), ('Naranja'), ('Marrón')
ON CONFLICT (nombre) DO NOTHING;

-- Insertar tipos de carrocería
INSERT INTO public.carrocerias (nombre) VALUES 
    ('Sedán'), ('SUV'), ('Pickup'), ('Van'), ('Hatchback'), 
    ('Wagon'), ('Coupe'), ('Convertible'), ('Truck'), ('Bus')
ON CONFLICT (nombre) DO NOTHING;

-- Insertar tipos de combustible
INSERT INTO public.combustibles (nombre) VALUES 
    ('Gasolina'), ('Diesel'), ('Eléctrico'), ('Híbrido'), ('Gas Natural'),
    ('Etanol'), ('Biodiesel'), ('Hidrógeno')
ON CONFLICT (nombre) DO NOTHING;

-- Insertar tipos de transmisión
INSERT INTO public.transmisiones (nombre) VALUES 
    ('Manual'), ('Automática'), ('CVT'), ('Semi-automática'), ('Tiptronic')
ON CONFLICT (nombre) DO NOTHING;

-- Insertar tipos de tracción
INSERT INTO public.tracciones (nombre) VALUES 
    ('Delantera'), ('Trasera'), ('4x4'), ('AWD'), ('4WD')
ON CONFLICT (nombre) DO NOTHING;

-- Insertar estados actuales básicos
INSERT INTO public.estados_actuales (nombre) VALUES 
    ('Disponible'), ('En Renta'), ('Mantenimiento'), ('Fuera de Servicio'),
    ('Reservado'), ('En Tránsito'), ('Vendido')
ON CONFLICT (nombre) DO NOTHING;

-- =====================================================
-- 5. CREAR ÍNDICES PARA OPTIMIZAR RENDIMIENTO
-- =====================================================

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_vehiculos_placa ON public.vehiculos(placa);
CREATE INDEX IF NOT EXISTS idx_vehiculos_vin ON public.vehiculos(vin);
CREATE INDEX IF NOT EXISTS idx_vehiculos_estatus ON public.vehiculos(estatus);
CREATE INDEX IF NOT EXISTS idx_vehiculos_arrendadora ON public.vehiculos(arrendadora_id);
CREATE INDEX IF NOT EXISTS idx_vehiculos_estado_inventario ON public.vehiculos(estado_inventario_id);

-- =====================================================
-- 6. VERIFICACIÓN FINAL
-- =====================================================

-- Verificar que todas las tablas se crearon correctamente
SELECT 'Tablas creadas:' as status, table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN (
    'carrocerias', 'colores', 'combustibles', 'transmisiones', 
    'tracciones', 'estados_actuales', 'vendedores', 'whatsapp_grupos', 'apoderados'
)
ORDER BY table_name;

-- Verificar estructura de la tabla vehiculos
SELECT column_name, data_type, is_nullable
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name = 'vehiculos'
ORDER BY ordinal_position;
